MasGlobal.Test/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MasGlobal.Test.Models
{
    public class EmployeeViewModel
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string ContractTypeName { get; set; }

        public int RoleId { get; set; }

        public string RoleName { get; set; }

        public string RoleDescripcion { get; set; }

        public double HourlySalary { get; set; }

        public double MonthlySalary { get; set; }

        public double AnualSalary { get; set; }

    }
}

MasGlobal.Test/Models/ErrorViewModel.cs
using System;

namespace MasGlobal.Test.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MasGlobal.Test/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MasGlobal.Test.Core;
using MasGlobal.Test.Core.DTOs;
using MasGlobal.Test.Core.Interfaces;
using MasGlobal.Test.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MasGlobal.Test.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class EmployeeController : ControllerBase
    {
        private readonly IEmployee employee;
        private readonly EmployeeFactory _employeeFactory;


        public EmployeeController(IEmployee employee, EmployeeFactory employeeFactory)
        {

            this.employee = employee;
            _employeeFactory = employeeFactory;


        }
        [HttpPost]
        public async Task<IActionResult> GetEmployees()
        {

            List<Employee> employeeList;

            try
            {

                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;


                if (!string.IsNullOrEmpty(searchValue))
                {
                    employeeList = await employee.GetEmployees(Convert.ToInt32(searchValue));

                }
                else
                {
                    employeeList = await employee.GetEmployees(0);

                }


                var model = (from p in employeeList
                             select new EmployeeViewModel()
                             {
                                 Id = p.Id,
                                 Name = p.Name,
                                 ContractTypeName = p.ContractTypeName,
                                 RoleId = p.RoleId,
                                 RoleName = p.RoleName,
                                 RoleDescripcion = p.RoleDescripcion,
                                 HourlySalary = p.HourlySalary,
                                 MonthlySalary = p.MonthlySalary,
                                 AnualSalary = _employeeFactory.GetSalary(p.ContractTypeName, p.MonthlySalary, p.HourlySalary).AnualSalaryEmployees()
                             }).ToList();

                var employeeData = model;

                recordsTotal = employeeData.Count();

                var data = employeeData.Skip(skip).Take(pageSize).ToList();

                var jsonData = new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data };

                return Ok(jsonData);



            }
            catch (Exception ex)
            {
                throw;
            }


        }

    }
}

MasGlobal.Test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MasGlobal.Test.Models;

namespace MasGlobal.Test.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MasGlobal.Test/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MasGlobal.Test.Core;
using MasGlobal.Test.Core.DTOs;
using MasGlobal.Test.Core.Interfaces;
using MasGlobal.Test.Data.Services;
using MasGlobal.Test.Models;
using Microsoft.AspNetCore.Mvc;

namespace MasGlobal.Test.Controllers
{
    public class SalaryController : Controller
    {
        private readonly IEmployee _employee;

        private readonly EmployeeFactory _employeeFactory;

        public SalaryController(IEmployee employee, EmployeeFactory employeeFactory)
        {

            _employee = employee;
            _employeeFactory = employeeFactory;
        }

        public async Task<IActionResult> Index(EmployeeViewModel emp)
        {

           
                var employees = await _employee.GetEmployees(emp.Id);

                var model = (from p in employees
                             select new EmployeeViewModel()
                             {
                                 Id = p.Id,
                                 Name = p.Name,
                                 ContractTypeName = p.ContractTypeName,
                                 RoleId = p.RoleId,
                                 RoleName = p.RoleName,
                                 RoleDescripcion = p.RoleDescripcion,
                                 HourlySalary = p.HourlySalary,
                                 MonthlySalary = p.MonthlySalary,
                                 AnualSalary = _employeeFactory.GetSalary(p.ContractTypeName, p.MonthlySalary, p.HourlySalary).AnualSalaryEmployees()


                             }).ToList();

                ViewBag.EmployeeList = model;

                return View();

        
        
        }
    }
}

MasGlobal.Test/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MasGlobal.Test/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MasGlobal.Test/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<div class="container">

    <br />
    <div style="width:90%; margin:0 auto;">
        <table id="employeeDatatable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>

                    <th>Id</th>
                    <th>Name</th>
                    <th>ContractTypeName</th>
                    <th>RoleId</th>
                    <th>RoleName</th>
                    <th>RoleDescripcion</th>
                    <th>HourlySalary</th>
                    <th>MonthlySalary</th>
                    <th>AnualSalary</th>

                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts
    {
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/employeeDatatable.js"></script>
}

MasGlobal.Test/Views/Salary/Index.cshtml
@*@model IEnumerable<MasGlobal.Test.Models.EmployeeViewModel>*@
@model MasGlobal.Test.Models.EmployeeViewModel


@{
    ViewData["Title"] = "Index";

    List<EmployeeViewModel> EmployeeList = ViewBag.EmployeeList;

}
<hr />

<div class="row">

    <div class="col-md-6">

        <form asp-action="Index" asp-controller="Salary" method="post">

            <div class="form-group">

                <label asp-for="Id"></label>
                <input type="text" class="form form-control" asp-for="Id" />

            </div>

            <div class="form-group">

                <input type="submit" value="Get Employees" class="btn btn-primary" />


            </div>
        </form>

    </div>

</div>

<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ContractTypeName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RoleId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RoleName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RoleDescripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HourlySalary)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MonthlySalary)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.AnualSalary)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in EmployeeList)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name

                    </td>
                    <td>
                        @item.ContractTypeName

                    </td>
                    <td>
                        @item.RoleId
                    </td>
                    <td>
                        @item.RoleName

                    </td>
                    <td>
                        @item.RoleDescripcion

                    </td>
                    <td>
                        @item.HourlySalary

                    </td>
                    <td>
                        @item.MonthlySalary

                    </td>

                    <td>
                        @item.AnualSalary

                    </td>

                </tr>
            }
        </tbody>
    </table>


</div>

MasGlobal.Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MasGlobal.Test</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MasGlobal.Test</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Employees</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - MasGlobal.Test</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>